In [1]:
import numpy as np
import pandas as pd
import os

# data_path = '../../../code_data/replace-bg/raw_data/DataTables'
# data_save_path = '../../../code_data/replace-bg/raw_data'
data_path = '../../../code_data/ctr3/raw_data/DataTables'
data_save_path = '../../../code_data/ctr3/'
process_file = 'coldstart_fl'
data_cgm = pd.read_csv(os.path.join(data_path, 'MonitorCGM.txt'),sep='|')
data_cgm

data_cgm['ts'] = pd.to_datetime(data_cgm['LocalDtTm'])
data_cgm.rename(columns={'CGM':'glucose_level', 'DeidentID':'pid'}, inplace=True)
data_cgm['glucose_level'] = data_cgm['glucose_level'].replace(0.0, np.nan)
data_cgm = data_cgm[['glucose_level', 'ts', 'pid']]
data_cgm.head()

   glucose_level                  ts  pid
0             93 2013-12-17 11:06:33    2
1             93 2013-12-17 11:01:33    2
2             93 2013-12-17 10:56:33    2
3             93 2013-12-17 10:51:33    2
4             94 2013-12-17 10:46:33    2

In [2]:
data_bgm = pd.read_csv(os.path.join(data_path, 'MonitorSMBG.txt'),sep='|')

data_bgm['ts'] = pd.to_datetime(data_bgm['LocalDtTm'])
data_bgm.rename(columns={'SMBG':'finger_stick', 'DeidentID':'pid'}, inplace=True)
data_bgm['finger_stick'] = data_bgm['finger_stick'].replace(0.0, np.nan)
data_bgm = data_bgm[['finger_stick', 'ts', 'pid']]
data_bgm.head()

   finger_stick                  ts  pid
0           153 2014-01-18 20:49:16    1
1           125 2014-01-18 17:58:17    1
2           295 2014-01-18 13:23:23    1
3           131 2014-01-18 08:47:56    1
4           237 2014-01-17 20:56:21    1

In [3]:
data_bolus = pd.read_csv(os.path.join(data_path, 'MonitorMealBolus.txt'),sep='|')

data_bolus['ts'] = pd.to_datetime(data_bolus['LocalDeliveredDtTm'])
data_bolus.rename(columns={'DeliveredValue':'bolus', 'DeidentID':'pid'}, inplace=True)
data_bolus['bolus'] = data_bolus['bolus'].replace(0.0, np.nan)
data_bolus = data_bolus[['bolus', 'ts', 'pid']]
data_bolus.head()

   bolus                  ts  pid
0   10.0 2013-12-17 06:36:11    2
1    8.0 2013-12-16 17:54:13    2
2    8.7 2014-08-18 06:48:32    3
3   10.3 2014-08-17 18:03:33    3
4   15.9 2014-08-17 12:08:34    3

In [4]:
data_corr_bolus = pd.read_csv(os.path.join(data_path, 'MonitorCorrectionBolus.txt'),sep='|')

data_corr_bolus['ts'] = pd.to_datetime(data_corr_bolus['LocalDeliveredDtTm'])
data_corr_bolus.rename(columns={'DeliveredValue':'correction_bolus', 'DeidentID':'pid'}, inplace=True)
data_corr_bolus['correction_bolus'] = data_corr_bolus['correction_bolus'].replace(0.0, np.nan)
data_corr_bolus = data_corr_bolus[['correction_bolus', 'ts', 'pid']]
data_corr_bolus.head()

   correction_bolus                  ts  pid
0               0.4 2013-12-17 06:36:11    2
1               2.5 2013-12-16 17:54:13    2
2               0.2 2013-12-16 17:40:25    2
3               4.1 2014-08-17 20:05:02    3
4               5.5 2014-08-17 15:48:03    3

In [5]:
data_basal = pd.read_csv(os.path.join(data_path, 'MonitorBasalBolus.txt'),sep='|')

data_basal['ts'] = pd.to_datetime(data_basal['LocalDeliveredDtTm'])
data_basal.rename(columns={'DeliveredValue':'basal', 'DeidentID':'pid'}, inplace=True)
data_basal['basal'] = data_basal['basal'].replace(0.0, np.nan)
data_basal = data_basal[['basal', 'ts', 'pid']]
data_basal.head()

   basal                  ts  pid
0    0.1 2013-12-17 11:05:23    2
1    0.1 2013-12-17 10:50:24    2
2    0.1 2013-12-17 10:25:24    2
3    0.1 2013-12-17 09:50:25    2
4    0.1 2013-12-17 09:40:25    2

In [6]:
data_meal = pd.read_csv(os.path.join(data_path, 'MonitorMeal.txt'),sep='|')

data_meal['ts'] = pd.to_datetime(data_meal['LocalDtTm'])
data_meal.rename(columns={'MealSize':'meal', 'DeidentID':'pid'}, inplace=True)
data_meal['meal'] = data_meal['meal'].replace(0.0, np.nan)
data_meal = data_meal[['meal', 'ts', 'pid']]
data_meal.head()

   meal                  ts  pid
0  80.0 2013-12-17 06:34:52    2
1  80.0 2013-12-16 17:52:50    2
2  35.0 2014-08-18 06:49:10    3
3  45.0 2014-08-17 18:04:07    3
4  70.0 2014-08-17 12:08:40    3

In [7]:

data_merge = data_cgm

for data in [data_bgm, data_bolus, data_corr_bolus, data_basal, data_meal]:
    data_merge = data_merge.merge(data, how='outer', on=['pid', 'ts'])

data_merge.head()

,glucose_level,ts,pid,finger_stick,bolus,correction_bolus,basal,meal
0,93.0,2013-12-17 11:06:33,2,NaN,NaN,NaN,NaN,NaN
1,93.0,2013-12-17 11:01:33,2,NaN,NaN,NaN,NaN,NaN
2,93.0,2013-12-17 10:56:33,2,NaN,NaN,NaN,NaN,NaN
3,93.0,2013-12-17 10:51:33,2,NaN,NaN,NaN,NaN,NaN
4,94.0,2013-12-17 10:46:33,2,NaN,NaN,NaN,NaN,NaN

In [8]:
data_merge.describe()

,glucose_level,pid,finger_stick,bolus,correction_bolus,basal,meal
count,915827.000000,1.540687e+06,3.056500e+04,12871.000000,2.169300e+04,5.747780e+05,13400.000000
mean,149.430097,1.208839e+01,2.811790e+05,4.083623,1.762499e+21,1.193249e-01,42.627313
std,52.488063,7.738052e+00,2.456554e+07,3.110006,2.595905e+23,6.554102e-02,26.980279
min,39.000000,1.000000e+00,1.000000e+00,0.002311,1.110220e-16,-8.881780e-16,1.000000
25%,112.000000,5.000000e+00,9.800000e+01,2.000000,6.000000e-01,1.000000e-01,25.000000
50%,141.000000,1.100000e+01,1.270000e+02,3.300000,1.100000e+00,1.000000e-01,38.000000
75%,178.000000,1.700000e+01,1.710000e+02,5.600000,2.000000e+00,1.000000e-01,55.000000
max,401.000000,3.000000e+01,2.147484e+09,18.000000,3.823390e+25,1.800000e+01,300.000000

In [9]:
import copy
import datetime
pid_list = list(set(data_merge['pid']))
pid2data = {}
for pid in pid_list:
    pid2data[pid] = copy.deepcopy(data_merge[data_merge['pid']==pid])
    pid2data[pid].set_index('ts', inplace=True)
    pid2data[pid] = pid2data[pid].sort_index()
    pid2data[pid] = pid2data[pid].drop(['pid'], axis=1)

In [10]:
# TODO should be removed
# pid2data = {2:pid2data[2], 284:pid2data[284]}
# pid_list = list(pid2data.keys())

In [11]:
def gen_5_mins_indicate_column(pid2data):
    pid2fivemins_indicat = {}
    for pid in pid2data:
        print(pid)
        gl_df = pid2data[pid].loc[:, 'glucose_level']
        temp_dict_list = []
        st = gl_df.index[0]
        idx = 0 
        while st <= gl_df.index[-1]:
            # get next ts
            while gl_df.index[idx] <= st:
                
                if idx == len(gl_df) - 1:
                    break
                idx += 1
                
            # add current ts
            temp_dict_list.append({'ts': st, '5_mins_indicate': 1})
            
            # if next ts is much further from the current ts
            # move to next
            if (gl_df.index[idx] - st) > datetime.timedelta(hours=2):
                st = gl_df.index[idx]
            else:
                st = st + datetime.timedelta(minutes=5)
        temp_dict_list.append({'ts': st, '5_mins_indicate': 1})
            
        temp_dict_list = pd.DataFrame(temp_dict_list)
        temp_dict_list.set_index('ts', inplace=True)
        pid2fivemins_indicat[pid] = temp_dict_list
    return pid2fivemins_indicat

In [12]:
pid2fivemins_indicat = gen_5_mins_indicate_column(pid2data)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30

In [13]:
def regularize_data(pid2data):


    new_pid2data = {}
    
    for pid in pid2data:
        print(pid)
        five_mins_indicate = pid2fivemins_indicat[pid].index
  
        new_data = []
        
        for ed in five_mins_indicate:
            temp_dict = {'ts':ed, }
            if ed == five_mins_indicate[0]:
                temp = pid2data[pid].loc[ed]
            else:
                temp = pid2data[pid].loc[ed-datetime.timedelta(seconds=299):ed].mean(skipna=True)
                
            for name in pid2data[pid].columns:
                temp_dict[name] = temp[name]
            if pd.notna(temp_dict['glucose_level']):
                temp_dict['glucose_level_indicate'] = 0
            else:
                temp_dict['glucose_level_indicate'] = 1
            new_data.append(temp_dict)
        new_pid2data[pid] = pd.DataFrame(new_data)
        new_pid2data[pid].set_index('ts', inplace=True)

    return new_pid2data

In [14]:
new_pid2data = regularize_data(pid2data)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30

In [15]:
new_pid2data[2].describe()

,glucose_level,finger_stick,bolus,correction_bolus,basal,meal,glucose_level_indicate
count,58724.000000,1795.000000,861.000000,1284.000000,4.198400e+04,761.000000,62421.000000
mean,147.638487,154.483380,5.337631,1.379773,1.130049e-01,43.710250,0.059227
std,43.044784,443.591728,2.844203,1.199328,4.250951e-02,20.688029,0.236051
min,39.000000,47.000000,0.400000,0.001406,-8.881780e-16,10.000000,0.000000
25%,117.000000,107.000000,3.100000,0.600000,1.000000e-01,30.000000,0.000000
50%,141.000000,136.000000,4.700000,1.200000,1.000000e-01,40.000000,0.000000
75%,173.000000,176.000000,7.200000,1.700000,1.000000e-01,57.000000,0.000000
max,401.000000,18811.000000,12.500000,14.000000,5.000000e-01,155.000000,1.000000

In [16]:
def add_time_attributes(pid2data):
    for pid in pid2data:
        data = pid2data[pid]

        data['date_temp'] = data.index

        data['day_of_week'] = data['date_temp'].dt.dayofweek
        data['day_of_week'] = data['day_of_week'].astype(float)

        data['week'] = data['date_temp'].dt.isocalendar().week
        data['week'] = data['week'].astype(float)

        data['year'] = data['date_temp'].dt.year
        data['year'] = data['year'].astype(float)


        data['hour'] = data['date_temp'].dt.hour
        data['hour'] = data['hour'].astype(float)

        data['minute'] = data['date_temp'].dt.minute
        data['minute'] = data['minute'].astype(float)

        # there is an error previously 360 -> 3600
        data['timestamp'] = data['date_temp'].dt.hour * 3600 +\
                                data['date_temp'].dt.minute * 60 +\
                                data['date_temp'].dt.second
        data['timestamp'] = data['timestamp'].astype(float)

        # new ————————————————————————
        seconds_in_day = 24*60*60

        data['sin_time'] = np.sin(2 * np.pi * data.timestamp / seconds_in_day)
        data['cos_time'] = np.cos(2 * np.pi * data.timestamp / seconds_in_day)
        data['sin_time'].astype(np.float64)
        data['cos_time'].astype(np.float64)
        # end ______________________


        pid2data[pid] = data.drop(['date_temp'], axis=1)
    
    return pid2data

In [17]:
new_pid2data = add_time_attributes(new_pid2data)

In [18]:
# add discrete y

def discrete(y):
    if y < 70:
        return 0
    elif 70<= y <=180:
        return 1
    elif y > 180:
        return 2
    else:
        return np.nan


def add_discrete_y(pid2data):
    for pid in pid2data:
        data = pid2data[pid]
        data['discrete_y'] = data['glucose_level']

        data['discrete_y'] = data['discrete_y'].apply(discrete)
        
    return pid2data

In [19]:
new_pid2data = add_discrete_y(new_pid2data)

In [20]:
pid2train = {}
pid2valid = {}
pid2test = {}
pid2regular_df = new_pid2data

for pid in pid2regular_df:
    idxs = pid2regular_df[pid].index[pd.notna(pid2regular_df[pid]['glucose_level'])]

    idxs = idxs.to_frame()

    total_len = len(idxs)
    train_end = int(total_len * 0.6)
    valid_end = int(total_len * 0.8) 

    pid2train[pid] = pid2regular_df[pid].loc[:idxs.iloc[train_end][0]]

    pid2valid[pid] = pid2regular_df[pid].loc[idxs.iloc[train_end + 1][0]:idxs.iloc[valid_end][0]]

    pid2test[pid] = pid2regular_df[pid].loc[idxs.iloc[valid_end + 1][0]:]

    print(pid, total_len, len(pid2train[pid]), len(pid2valid[pid]), len(pid2test[pid]))

1 12242 7642 2518 2535
2 58724 38081 12256 12084
3 50310 30975 10552 11062
4 60663 37246 12620 12439
5 57302 35755 11844 12299
6 37842 23578 8021 8091
7 51188 32946 11225 11817
8 49412 30936 10396 10413
9 17598 11420 4538 3957
10 35061 22850 7943 7994
11 52583 32935 13250 10766
12 12882 8293 2749 2755
13 42630 26675 8900 8853
14 47275 30117 9787 11693
15 51659 31640 11070 10799
16 13974 9445 2857 2836
17 46412 28849 9547 9616
18 13830 8487 2804 2821
19 13109 8100 2844 2789
20 52012 32471 10670 10678
21 11869 7862 2967 2548
22 14056 8730 2918 3000
23 13417 8702 2784 2870
24 13657 8823 3230 2864
25 11850 7976 2472 2496
26 13911 9262 2843 2949
27 14907 9129 3053 3125
28 16238 10460 3384 3453
29 15279 9534 3100 3178
30 12877 8005 2640 2882

In [21]:
pid_attri2mean_std = {}
attris_should_norm = ['glucose_level', 'bolus', 'correction_bolus', 'basal', 'meal',
       'finger_stick', 'timestamp']
for pid in pid_list:
    for attri in attris_should_norm:
        mean = pid2train[pid][attri].mean()
        std = pid2train[pid][attri].std()
        if std is np.NaN or std is pd.NaT or std == 0:
            std = 1e-6
        pid_attri2mean_std[(pid, attri)] = (mean, std)

if not os.path.exists(os.path.join(data_save_path, process_file)):
    os.makedirs(os.path.join(data_save_path, process_file))
np.save(os.path.join(data_save_path, process_file, 'pid_attri2mean_std.npy'), pid_attri2mean_std)

In [22]:
def norm_data(pid2data, pid_attri2mean_std, attris_should_norm):

    new_pid2data = {}
    for pid in pid2data:

        new_pid2data[pid] = copy.deepcopy(pid2data[pid]) 

        for attri in attris_should_norm:

            mean, std = pid_attri2mean_std[(pid, attri)]

            if std <= 1e-6:
                new_pid2data[pid][attri] = new_pid2data[pid][attri] / mean
            else:
                new_pid2data[pid][attri] = (new_pid2data[pid][attri] - mean) / std          

    return new_pid2data

pid2train_norm = norm_data(pid2train, pid_attri2mean_std, attris_should_norm)
pid2valid_norm = norm_data(pid2valid, pid_attri2mean_std, attris_should_norm)
pid2test_norm = norm_data(pid2test, pid_attri2mean_std, attris_should_norm)

In [23]:
attri_list_wo_glucose = [ 'bolus', 'correction_bolus', 'basal', 'meal',
       'finger_stick',  'day_of_week', 'hour', 'minute', 'timestamp',
    'sin_time', 'cos_time', 'glucose_level_indicate'
]

temp = []

for idx, attri in enumerate(attri_list_wo_glucose):
    temp.append({'attri':attri, 'idx':idx} )
attri2idx = pd.DataFrame(temp).set_index('attri')
idx2attri = pd.DataFrame(temp).set_index('idx')
print(attri2idx)
print(idx2attri)

save_path = os.path.join(data_save_path, process_file)

attri2idx.to_pickle(os.path.join(save_path,'attri2idx.pkl'))
idx2attri.to_pickle(os.path.join(save_path,'idx2attri.pkl'))

                        idx
attri
bolus                     0
correction_bolus          1
basal                     2
meal                      3
finger_stick              4
day_of_week               5
hour                      6
minute                    7
timestamp                 8
sin_time                  9
cos_time                 10
glucose_level_indicate   11
                      attri
idx
0                     bolus
1          correction_bolus
2                     basal
3                      meal
4              finger_stick
5               day_of_week
6                      hour
7                    minute
8                 timestamp
9                  sin_time
10                 cos_time
11   glucose_level_indicate

In [24]:
for pid in pid_list:
    pid2train_norm[pid] = pid2train_norm[pid].fillna(0.0)
    pid2valid_norm[pid] = pid2valid_norm[pid].fillna(0.0)
    pid2test_norm[pid] = pid2test_norm[pid].fillna(0.0)

In [25]:
# generate training data


def gen_final(pid2data, attri2idx,  n_prev, pred_window, name, valid_points = 24): 
    pid2data_npy = {}
    for pid in pid_list:
        data = pid2data[pid]
        
        y_list = []
        y_dis_list = []
        target_cos_time_list = []
        target_sin_time_list = []
        target_total_seconds_list = []
        attri_X_list = []

        glucose_level_X_list = []
        
        seq_st_ed_list = []
        
        seq_st, seq_ed = None, None


        for idx in range(len(data) - n_prev - pred_window + 1):
            glucose_level_y = data.iloc[idx + n_prev + pred_window - 1]['glucose_level']
            glucose_level_y_indicate = data.iloc[idx + n_prev + pred_window - 1]['glucose_level_indicate']
            if abs(glucose_level_y_indicate - 1) < 1e-6:
                continue
            
            not_consecutive = (data.index[idx + n_prev + pred_window - 1] - data.index[idx]) != datetime.timedelta(minutes=pred_window*5+n_prev*5 - 5)
            
            # Resonable
            num_valids = int(valid_points - sum(data.iloc[idx + n_prev - valid_points : idx + n_prev]['glucose_level_indicate']))
            if num_valids == 0 or not_consecutive:
                if seq_st is not None and seq_ed - seq_st >= 2:
                    seq_st_ed_list.append([seq_st, seq_ed])
                seq_st, seq_ed = None, None
                continue
            # end

            
            y_list.append(glucose_level_y)
            y_dis_list.append(data.iloc[idx + n_prev + pred_window - 1]['discrete_y'])
            target_cos_time_list.append(data.iloc[idx + n_prev + pred_window - 1]['cos_time'])
            target_sin_time_list.append(data.iloc[idx + n_prev + pred_window - 1]['sin_time'])
            target_total_seconds_list.append(data.iloc[idx + n_prev + pred_window - 1]['timestamp'])
            glucose_level_X = np.array(data.iloc[idx: idx + n_prev]['glucose_level'].to_numpy(), dtype=np.float32)


            attri_X = np.array(data.iloc[idx: idx + n_prev][list(attri2idx.index)].to_numpy(), dtype=np.float32)          

            glucose_level_X_list.append(np.expand_dims(glucose_level_X, axis=0))

            attri_X_list.append(np.expand_dims(attri_X, axis=0))


            if seq_st is None:
                seq_st = len(y_list) - 1
                seq_ed = len(y_list) - 1
            else:
                seq_ed = len(y_list) - 1

        if seq_st is not None and seq_ed - seq_st >= 2:
            seq_st_ed_list.append([seq_st, seq_ed])

        pid2data_npy[pid] = {}
        pid2data_npy[pid]['glucose_level_X'] = np.concatenate(glucose_level_X_list, axis=0)

        pid2data_npy[pid]['attri_X'] = np.concatenate(attri_X_list, axis=0)
        pid2data_npy[pid]['y'] = np.array(y_list, dtype=np.float32)
        pid2data_npy[pid]['y_dis'] = np.array(y_dis_list, dtype=np.int32)
        pid2data_npy[pid]['target_cos_time'] = np.array(target_cos_time_list, dtype=np.float32)
        pid2data_npy[pid]['target_sin_time'] = np.array(target_sin_time_list, dtype=np.float32)
        pid2data_npy[pid]['target_timestamp'] = np.array(target_total_seconds_list, dtype=np.float32)
        pid2data_npy[pid]['mean'] = pid_attri2mean_std[(pid, 'glucose_level')][0]
        pid2data_npy[pid]['std'] = pid_attri2mean_std[(pid, 'glucose_level')][1]

        pid2data_npy[pid]['seq_st_ed_list'] = np.array(seq_st_ed_list, dtype=np.int32)

        print(pid, pid2data_npy[pid]['glucose_level_X'].shape, pid2data_npy[pid]['attri_X'].shape)
        print('    ',len(y_list), seq_st_ed_list)
    save_path = os.path.join(data_save_path, process_file)
    np.save(os.path.join(save_path, f'{name}_{n_prev}_{pred_window}.npy'), pid2data_npy)

In [26]:
gen_final(pid2train_norm, attri2idx,  n_prev=24, pred_window=6, name='train_pid2data_npy', valid_points = 12)

1 (7234, 24) (7234, 24, 12)
     7234 [[0, 1929], [1930, 3604], [3605, 4879], [4880, 5149], [5150, 5396], [5397, 5537], [5538, 7028], [7029, 7233]]
2 (34976, 24) (34976, 24, 12)
     34976 [[0, 1639], [1642, 1826], [1827, 3765], [3766, 3783], [3784, 5628], [5629, 5656], [5657, 7465], [7466, 9437], [9438, 10530], [10531, 12488], [12489, 12775], [12776, 14354], [14355, 16317], [16318, 18275], [18276, 20237], [20238, 22162], [22163, 22237], [22238, 24135], [24136, 26103], [26104, 26175], [26176, 27919], [27920, 29301], [29302, 31232], [31233, 31447], [31448, 33419], [33420, 34302], [34303, 34975]]
3 (29936, 24) (29936, 24, 12)
     29936 [[0, 1934], [1935, 3065], [3066, 3321], [3322, 4498], [4499, 5321], [5322, 7221], [7222, 9187], [9188, 10042], [10043, 11745], [11746, 12019], [12020, 13969], [13970, 15942], [15943, 17903], [17904, 19611], [19612, 21063], [21064, 21232], [21233, 21448], [21449, 21965], [21966, 23355], [23356, 25331], [25332, 26763], [26764, 28192], [28193, 29935]]
4 (36105, 24) (36105, 24, 12)
     36105 [[0, 1951], [1952, 1965], [1966, 2441], [2442, 3353], [3354, 5220], [5221, 5547], [5548, 5664], [5665, 6220], [6221, 6571], [6572, 8034], [8035, 10002], [10003, 11129], [11130, 12305], [12306, 14228], [14229, 16172], [16173, 18138], [18139, 20088], [20089, 21956], [21957, 23884], [23885, 25863], [25864, 27833], [27834, 29807], [29808, 31755], [31756, 33468], [33469, 33641], [33642, 35606], [35607, 36104]]
5 (34045, 24) (34045, 24, 12)
     34045 [[0, 1927], [1928, 1965], [1966, 3365], [3366, 3379], [3380, 5121], [5122, 5283], [5284, 5459], [5460, 5546], [5547, 7066], [7067, 7257], [7258, 8911], [8912, 10873], [10874, 11143], [11144, 11517], [11518, 12039], [12040, 13986], [13987, 14118], [14119, 14325], [14326, 14339], [14340, 14591], [14592, 14777], [14778, 14814], [14815, 15390], [15391, 15523], [15524, 17492], [17493, 19462], [19463, 21433], [21434, 23412], [23413, 25384], [25385, 27340], [27341, 29275], [29276, 29539], [29540, 31231], [31232, 32772], [32773, 32971], [32972, 34044]]
6 (22394, 24) (22394, 24, 12)
     22394 [[0, 1157], [1158, 1942], [1943, 3192], [3193, 5128], [5129, 7034], [7035, 8967], [8968, 10412], [10413, 11429], [11430, 11684], [11685, 13606], [13607, 14977], [14978, 16298], [16299, 16303], [16304, 18117], [18118, 20028], [20029, 21997], [21998, 22393]]
7 (30334, 24) (30334, 24, 12)
     30334 [[0, 451], [452, 1586], [1587, 1875], [1876, 2537], [2538, 3429], [3430, 4420], [4421, 6329], [6330, 8229], [8230, 10099], [10100, 11204], [11205, 11676], [11677, 11790], [11791, 13537], [13538, 14133], [14134, 14931], [14932, 16814], [16815, 18377], [18378, 18680], [18681, 18857], [18858, 19597], [19598, 20670], [20671, 21994], [21995, 22556], [22557, 23096], [23097, 24990], [24991, 25594], [25595, 25978], [25979, 25983], [25984, 25991], [25992, 26500], [26501, 27751], [27752, 28963], [28964, 29420], [29421, 29804], [29805, 30333]]
8 (29314, 24) (29314, 24, 12)
     29314 [[0, 1662], [1663, 2351], [2352, 4202], [4203, 4254], [4255, 5630], [5631, 5766], [5767, 6227], [6228, 6485], [6486, 7492], [7493, 9314], [9315, 9549], [9550, 10460], [10461, 12182], [12183, 14139], [14140, 14653], [14654, 16256], [16257, 18207], [18208, 20175], [20176, 21391], [21392, 23347], [23348, 24268], [24269, 25128], [25129, 26471], [26472, 27428], [27429, 28179], [28180, 29313]]
9 (10389, 24) (10389, 24, 12)
     10389 [[0, 259], [260, 1343], [1344, 2060], [2061, 2191], [2192, 2814], [2815, 3070], [3071, 3168], [3169, 5073], [5074, 5576], [5577, 5969], [5970, 6539], [6540, 8408], [8409, 9935], [9936, 10111], [10112, 10388]]
10 (20544, 24) (20544, 24, 12)
     20544 [[0, 261], [262, 295], [296, 2224], [2225, 4177], [4178, 5296], [5297, 6078], [6079, 6928], [6929, 6983], [6984, 7093], [7094, 9050], [9051, 9423], [9424, 9782], [9783, 10102], [10103, 11382], [11383, 11718], [11719, 11897], [11898, 11962], [11965, 12290], [12291, 13637], [13638, 13756], [13757, 14626], [14627, 14645], [14646, 16176], [16177, 16413], [16414, 17302], [17303, 17641], [17642, 18408], [18409, 18645], [18646, 18931], [18932, 19294], [19295, 19496], [19497, 19553], [19554, 19981], [19982, 20543]]
11 (31319, 24) (31319, 24, 12)
     31319 [[0, 1629], [1630, 2751], [2752, 4543], [4544, 6502], [6503, 8451], [8452, 10432], [10433, 12415], [12416, 13491], [13492, 13777], [13778, 15688], [15689, 17477], [17478, 18837], [18838, 20458], [20459, 22384], [22385, 22814], [22815, 22882], [22883, 24794], [24795, 25063], [25064, 26116], [26117, 28095], [28096, 29291], [29292, 31268], [31269, 31318]]
12 (7604, 24) (7604, 24, 12)
     7604 [[0, 1436], [1437, 2616], [2617, 3203], [3204, 3706], [3707, 4813], [4814, 4961], [4962, 5587], [5588, 5663], [5664, 5927], [5928, 6472], [6473, 7075], [7076, 7603]]
13 (25242, 24) (25242, 24, 12)
     25242 [[0, 1523], [1524, 3177], [3178, 3284], [3285, 3414], [3415, 4835], [4836, 6533], [6534, 8476], [8477, 9930], [9931, 10375], [10376, 12323], [12324, 13942], [13943, 15589], [15590, 17487], [17488, 17769], [17770, 18079], [18080, 18966], [18967, 19324], [19325, 19735], [19736, 20107], [20108, 21561], [21562, 22252], [22253, 23185], [23186, 25133], [25134, 25241]]
14 (28042, 24) (28042, 24, 12)
     28042 [[0, 110], [111, 181], [182, 660], [661, 973], [974, 1687], [1688, 2157], [2158, 3062], [3063, 3216], [3217, 3695], [3696, 4237], [4238, 4905], [4906, 6158], [6159, 7746], [7747, 7872], [7873, 9821], [9822, 9933], [9934, 11105], [11106, 11126], [11127, 12711], [12712, 12878], [12879, 14814], [14815, 16722], [16723, 18602], [18603, 18728], [18729, 19294], [19295, 19705], [19706, 20547], [20548, 22327], [22328, 22568], [22569, 23221], [23222, 23459], [23460, 23749], [23750, 25214], [25215, 27096], [27097, 28041]]
15 (30774, 24) (30774, 24, 12)
     30774 [[0, 21], [22, 1997], [1998, 3368], [3369, 4926], [4927, 6866], [6867, 8815], [8816, 9259], [9260, 9966], [9967, 10136], [10137, 12098], [12099, 14049], [14050, 14199], [14200, 15941], [15942, 17921], [17922, 19902], [19903, 21872], [21873, 23849], [23850, 25782], [25783, 27042], [27043, 29026], [29027, 30773]]
16 (8268, 24) (8268, 24, 12)
     8268 [[0, 751], [752, 891], [892, 2430], [2431, 2509], [2510, 2953], [2954, 4026], [4027, 6004], [6005, 7949], [7950, 8267]]
17 (27530, 24) (27530, 24, 12)
     27530 [[0, 1441], [1442, 2030], [2031, 2279], [2280, 2427], [2428, 2845], [2846, 3453], [3454, 4765], [4766, 5362], [5363, 6670], [6671, 7260], [7261, 7806], [7807, 9782], [9783, 10389], [10390, 11686], [11687, 11938], [11939, 13911], [13912, 14567], [14568, 16093], [16094, 16178], [16179, 16483], [16485, 18390], [18391, 20334], [20335, 22252], [22253, 24143], [24144, 26115], [26116, 27529]]
18 (8197, 24) (8197, 24, 12)
     8197 [[0, 1338], [1339, 1983], [1984, 2416], [2417, 4085], [4086, 6063], [6064, 8032], [8033, 8070], [8071, 8196]]
19 (7764, 24) (7764, 24, 12)
     7764 [[0, 1361], [1362, 2116], [2117, 2555], [2556, 3909], [3910, 5880], [5881, 7763]]
20 (30876, 24) (30876, 24, 12)
     30876 [[0, 1334], [1335, 2436], [2437, 2445], [2446, 2873], [2874, 3053], [3054, 4998], [4999, 6965], [6966, 7855], [7856, 9056], [9057, 10506], [10507, 12469], [12470, 12583], [12584, 14022], [14023, 14116], [14117, 14620], [14621, 16579], [16580, 18232], [18233, 18487], [18488, 18506], [18507, 20476], [20477, 21763], [21764, 23385], [23386, 23573], [23574, 25283], [25284, 27168], [27169, 27637], [27638, 28285], [28286, 30135], [30136, 30875]]
21 (6974, 24) (6974, 24, 12)
     6974 [[0, 1461], [1462, 1482], [1485, 1749], [1750, 3043], [3044, 4089], [4090, 4293], [4294, 4379], [4380, 4980], [4981, 5137], [5138, 5182], [5183, 5974], [5975, 6973]]
22 (8353, 24) (8353, 24, 12)
     8353 [[0, 1270], [1271, 3165], [3166, 5121], [5122, 6311], [6312, 8257], [8258, 8352]]
23 (7965, 24) (7965, 24, 12)
     7965 [[0, 543], [544, 1097], [1098, 1156], [1157, 1332], [1333, 1640], [1641, 1667], [1668, 2942], [2943, 3145], [3146, 5029], [5030, 6109], [6110, 6919], [6920, 7964]]
24 (8136, 24) (8136, 24, 12)
     8136 [[0, 1462], [1463, 3388], [3389, 3952], [3953, 5901], [5902, 6521], [6522, 7520], [7521, 8135]]
25 (7047, 24) (7047, 24, 12)
     7047 [[0, 19], [20, 218], [219, 865], [866, 2537], [2538, 4488], [4489, 6101], [6102, 7046]]
26 (8293, 24) (8293, 24, 12)
     8293 [[0, 1032], [1033, 1245], [1246, 2341], [2342, 4315], [4316, 5915], [5916, 7878], [7879, 8292]]
27 (8720, 24) (8720, 24, 12)
     8720 [[0, 1396], [1397, 2536], [2537, 3562], [3563, 4159], [4160, 6133], [6134, 6279], [6280, 7117], [7118, 8194], [8195, 8200], [8201, 8719]]
28 (9622, 24) (9622, 24, 12)
     9622 [[0, 612], [613, 1394], [1395, 3160], [3161, 3298], [3299, 3568], [3569, 3585], [3586, 5157], [5158, 5391], [5392, 5430], [5431, 6289], [6290, 7158], [7159, 7180], [7181, 9133], [9134, 9621]]
29 (9063, 24) (9063, 24, 12)
     9063 [[0, 862], [863, 1323], [1324, 1845], [1846, 2106], [2107, 3245], [3246, 4409], [4410, 4743], [4744, 5059], [5060, 6719], [6720, 6907], [6908, 8674], [8675, 9062]]
30 (7658, 24) (7658, 24, 12)
     7658 [[0, 1570], [1571, 3534], [3535, 4838], [4839, 5081], [5082, 7004], [7005, 7657]]

In [27]:
gen_final(pid2train_norm, attri2idx,  n_prev=24, pred_window=12, name='train_pid2data_npy', valid_points = 12)

1 (7192, 24) (7192, 24, 12)
     7192 [[0, 1923], [1924, 3592], [3593, 4861], [4862, 5125], [5126, 5366], [5367, 5507], [5508, 6992], [6993, 7191]]
2 (34821, 24) (34821, 24, 12)
     34821 [[0, 1633], [1634, 1812], [1813, 3745], [3746, 3757], [3758, 5596], [5597, 5618], [5619, 7421], [7422, 9387], [9388, 10474], [10475, 12426], [12427, 12707], [12708, 14280], [14281, 16237], [16238, 18189], [18190, 20145], [20146, 22064], [22065, 22133], [22134, 24025], [24026, 25987], [25988, 26053], [26054, 27791], [27792, 29167], [29168, 31092], [31093, 31301], [31302, 33269], [33270, 34152], [34153, 34820]]
3 (29807, 24) (29807, 24, 12)
     29807 [[0, 1928], [1929, 3053], [3054, 3303], [3304, 4474], [4475, 5291], [5292, 7187], [7188, 9147], [9148, 9996], [9997, 11693], [11694, 11961], [11962, 13905], [13906, 15872], [15873, 17827], [17828, 19529], [19530, 20975], [20976, 21138], [21139, 21349], [21350, 21866], [21867, 23250], [23251, 25220], [25221, 26646], [26647, 28069], [28070, 29806]]
4 (35956, 24) (35956, 24, 12)
     35956 [[0, 1945], [1946, 1954], [1955, 2424], [2425, 3330], [3331, 5191], [5192, 5512], [5513, 5629], [5630, 6179], [6180, 6524], [6525, 7981], [7982, 9943], [9944, 11064], [11065, 12234], [12235, 14151], [14152, 16089], [16090, 18049], [18050, 19993], [19994, 21855], [21856, 23777], [23778, 25750], [25751, 27714], [27715, 29682], [29683, 31624], [31625, 33337], [33338, 33504], [33505, 35463], [35464, 35955]]
5 (33860, 24) (33860, 24, 12)
     33860 [[0, 1921], [1922, 1953], [1954, 3347], [3348, 3355], [3356, 5091], [5092, 5247], [5248, 5417], [5418, 5498], [5499, 7012], [7013, 7197], [7198, 8845], [8846, 10801], [10802, 11065], [11066, 11433], [11434, 11949], [11950, 13890], [13891, 14017], [14018, 14224], [14225, 14238], [14239, 14484], [14485, 14670], [14671, 14707], [14708, 15277], [15278, 15404], [15405, 17367], [17368, 19331], [19332, 21296], [21297, 23269], [23270, 25235], [25236, 27185], [27186, 29114], [29115, 29378], [29379, 31064], [31065, 32599], [32600, 32792], [32793, 33859]]
6 (22305, 24) (22305, 24, 12)
     22305 [[0, 1151], [1152, 1930], [1931, 3174], [3175, 5104], [5105, 7004], [7005, 8931], [8932, 10370], [10371, 11387], [11388, 11636], [11637, 13552], [13553, 14917], [14918, 16232], [16233, 16236], [16237, 18045], [18046, 19950], [19951, 21913], [21914, 22304]]
7 (30183, 24) (30183, 24, 12)
     30183 [[0, 445], [446, 1577], [1578, 1860], [1861, 2518], [2519, 3410], [3411, 4395], [4396, 6298], [6299, 8192], [8193, 10056], [10057, 11155], [11156, 11622], [11623, 11736], [11737, 13477], [13478, 14067], [14068, 14859], [14860, 16736], [16737, 18300], [18301, 18597], [18598, 18770], [18771, 19504], [19505, 20571], [20572, 21896], [21897, 22452], [22453, 22986], [22987, 24874], [24875, 25477], [25478, 25859], [25860, 25866], [25869, 26372], [26373, 27617], [27618, 28825], [28826, 29277], [29278, 29659], [29660, 30182]]
8 (29159, 24) (29159, 24, 12)
     29159 [[0, 1656], [1657, 2339], [2340, 4184], [4185, 4230], [4231, 5600], [5601, 5730], [5731, 6185], [6186, 6437], [6438, 7439], [7440, 9255], [9256, 9484], [9485, 10389], [10390, 12105], [12106, 14056], [14057, 14564], [14565, 16161], [16162, 18106], [18107, 20068], [20069, 21278], [21279, 23228], [23229, 24143], [24144, 24997], [24998, 26334], [26335, 27285], [27286, 28030], [28031, 29158]]
9 (10310, 24) (10310, 24, 12)
     10310 [[0, 253], [254, 1337], [1338, 2048], [2049, 2173], [2174, 2790], [2791, 3042], [3043, 3134], [3135, 5033], [5034, 5530], [5531, 5917], [5918, 6481], [6482, 8344], [8345, 9865], [9866, 10035], [10036, 10309]]
10 (20363, 24) (20363, 24, 12)
     20363 [[0, 255], [256, 285], [286, 2210], [2211, 4157], [4158, 5270], [5271, 6046], [6047, 6890], [6891, 6939], [6940, 7043], [7044, 8994], [8995, 9361], [9362, 9714], [9715, 10028], [10029, 11302], [11303, 11632], [11633, 11805], [11806, 11864], [11865, 12187], [12188, 13528], [13529, 13641], [13642, 14505], [14506, 14522], [14523, 16047], [16048, 16285], [16286, 17168], [17169, 17507], [17508, 18268], [18269, 18500], [18501, 18780], [18781, 19137], [19138, 19333], [19334, 19384], [19385, 19806], [19807, 20362]]
11 (31184, 24) (31184, 24, 12)
     31184 [[0, 1623], [1624, 2739], [2740, 4525], [4526, 6478], [6479, 8421], [8422, 10396], [10397, 12373], [12374, 13443], [13444, 13723], [13724, 15628], [15629, 17411], [17412, 18765], [18766, 20380], [20381, 22300], [22301, 22724], [22725, 22789], [22790, 24695], [24696, 24958], [24959, 26005], [26006, 27978], [27979, 29168], [29169, 31139], [31140, 31183]]
12 (7551, 24) (7551, 24, 12)
     7551 [[0, 1430], [1431, 2604], [2605, 3185], [3186, 3682], [3683, 4788], [4789, 4938], [4939, 5558], [5559, 5634], [5635, 5892], [5893, 6431], [6432, 7028], [7029, 7550]]
13 (25113, 24) (25113, 24, 12)
     25113 [[0, 1517], [1518, 3165], [3166, 3277], [3278, 3401], [3402, 4816], [4817, 6508], [6509, 8445], [8446, 9897], [9898, 10336], [10337, 12278], [12279, 13891], [13892, 15532], [15533, 17424], [17425, 17700], [17701, 18004], [18005, 18885], [18886, 19237], [19238, 19642], [19643, 20008], [20009, 21456], [21457, 22141], [22142, 23068], [23069, 25010], [25011, 25112]]
14 (27872, 24) (27872, 24, 12)
     27872 [[0, 104], [105, 169], [170, 642], [643, 949], [950, 1657], [1658, 2121], [2122, 3020], [3021, 3169], [3170, 3648], [3649, 4184], [4185, 4852], [4853, 6099], [6100, 7687], [7688, 7807], [7808, 9750], [9751, 9862], [9863, 11034], [11035, 11049], [11050, 12628], [12629, 12789], [12790, 14719], [14720, 16621], [16622, 18495], [18496, 18615], [18616, 19175], [19176, 19580], [19581, 20416], [20417, 22190], [22191, 22429], [22430, 23076], [23077, 23313], [23314, 23597], [23598, 25056], [25057, 26932], [26933, 27871]]
15 (30654, 24) (30654, 24, 12)
     30654 [[0, 15], [16, 1985], [1986, 3350], [3351, 4902], [4903, 6836], [6837, 8779], [8780, 9217], [9218, 9924], [9925, 10088], [10089, 12044], [12045, 13989], [13990, 14133], [14134, 15869], [15870, 17843], [17844, 19818], [19819, 21782], [21783, 23753], [23754, 25680], [25681, 26934], [26935, 28912], [28913, 30653]]
16 (8220, 24) (8220, 24, 12)
     8220 [[0, 745], [746, 879], [880, 2412], [2413, 2491], [2492, 2929], [2930, 3996], [3997, 5968], [5969, 7907], [7908, 8219]]
17 (27381, 24) (27381, 24, 12)
     27381 [[0, 1435], [1436, 2018], [2019, 2261], [2262, 2403], [2404, 2815], [2816, 3417], [3418, 4723], [4724, 5314], [5315, 6616], [6617, 7200], [7201, 7740], [7741, 9710], [9711, 10311], [10312, 11602], [11603, 11848], [11849, 13815], [13816, 14465], [14466, 15985], [15986, 16064], [16065, 16371], [16372, 18271], [18272, 20209], [20210, 22121], [22122, 24006], [24007, 25972], [25973, 27380]]
18 (8150, 24) (8150, 24, 12)
     8150 [[0, 1332], [1333, 1971], [1972, 2398], [2399, 4061], [4062, 6033], [6034, 7997], [7998, 8029], [8030, 8149]]
19 (7728, 24) (7728, 24, 12)
     7728 [[0, 1355], [1356, 2104], [2105, 2537], [2538, 3885], [3886, 5850], [5851, 7727]]
20 (30726, 24) (30726, 24, 12)
     30726 [[0, 1328], [1329, 2424], [2425, 2435], [2436, 2857], [2858, 3031], [3032, 4970], [4971, 6931], [6932, 7815], [7816, 9011], [9012, 10455], [10456, 12412], [12413, 12527], [12528, 13964], [13965, 14052], [14053, 14550], [14551, 16503], [16504, 18150], [18151, 18399], [18400, 18412], [18413, 20376], [20377, 21657], [21658, 23273], [23274, 23457], [23458, 25161], [25162, 27040], [27041, 27503], [27504, 28145], [28146, 29989], [29990, 30725]]
21 (6909, 24) (6909, 24, 12)
     6909 [[0, 1456], [1457, 1462], [1463, 1476], [1477, 1735], [1736, 3023], [3024, 4063], [4064, 4261], [4262, 4344], [4345, 4939], [4940, 5090], [5091, 5129], [5130, 5915], [5916, 6908]]
22 (8317, 24) (8317, 24, 12)
     8317 [[0, 1264], [1265, 3153], [3154, 5103], [5104, 6287], [6288, 8227], [8228, 8316]]
23 (7907, 24) (7907, 24, 12)
     7907 [[0, 539], [540, 1089], [1090, 1142], [1143, 1316], [1317, 1618], [1619, 1639], [1640, 2914], [2915, 3111], [3112, 4989], [4990, 6063], [6064, 6867], [6868, 7906]]
24 (8094, 24) (8094, 24, 12)
     8094 [[0, 1456], [1457, 3376], [3377, 3934], [3935, 5877], [5878, 6491], [6492, 7484], [7485, 8093]]
25 (7005, 24) (7005, 24, 12)
     7005 [[0, 13], [14, 206], [207, 847], [848, 2513], [2514, 4458], [4459, 6065], [6066, 7004]]
26 (8252, 24) (8252, 24, 12)
     8252 [[0, 1026], [1027, 1233], [1234, 2323], [2324, 4291], [4292, 5886], [5887, 7843], [7844, 8251]]
27 (8660, 24) (8660, 24, 12)
     8660 [[0, 1390], [1391, 2524], [2525, 3544], [3545, 4135], [4136, 6103], [6104, 6243], [6244, 7075], [7076, 8146], [8147, 8659]]
28 (9565, 24) (9565, 24, 12)
     9565 [[0, 612], [613, 1388], [1389, 3148], [3149, 3282], [3283, 3552], [3553, 3563], [3564, 5129], [5130, 5363], [5364, 5396], [5397, 6249], [6250, 7117], [7118, 7133], [7134, 9082], [9083, 9564]]
29 (9017, 24) (9017, 24, 12)
     9017 [[0, 862], [863, 1317], [1318, 1834], [1835, 2095], [2096, 3228], [3229, 4389], [4390, 4720], [4721, 5030], [5031, 6685], [6686, 6873], [6874, 8634], [8635, 9016]]
30 (7623, 24) (7623, 24, 12)
     7623 [[0, 1565], [1566, 3523], [3524, 4821], [4822, 5058], [5059, 6975], [6976, 7622]]

In [28]:
gen_final(pid2valid_norm, attri2idx,  n_prev=24, pred_window=6, name='valid_pid2data_npy', valid_points = 12)

1 (2414, 24) (2414, 24, 12)
     2414 [[0, 1712], [1713, 2413]]
2 (11666, 24) (11666, 24, 12)
     11666 [[0, 356], [357, 2275], [2276, 4227], [4228, 6180], [6181, 6379], [6380, 7849], [7850, 8552], [8553, 10233], [10234, 11665]]
3 (9942, 24) (9942, 24, 12)
     9942 [[0, 171], [172, 675], [676, 1206], [1207, 1434], [1435, 1938], [1939, 3272], [3273, 5199], [5200, 5683], [5684, 7325], [7326, 9276], [9277, 9941]]
4 (12028, 24) (12028, 24, 12)
     12028 [[0, 842], [843, 2793], [2794, 2835], [2836, 4766], [4767, 6672], [6673, 8481], [8482, 8554], [8555, 10529], [10530, 11093], [11094, 12027]]
5 (11389, 24) (11389, 24, 12)
     11389 [[0, 853], [854, 1154], [1155, 2708], [2709, 4668], [4669, 6647], [6648, 8610], [8611, 10561], [10562, 11388]]
6 (7480, 24) (7480, 24, 12)
     7480 [[0, 488], [489, 1320], [1321, 3247], [3248, 3256], [3257, 3951], [3952, 5142], [5143, 7106], [7107, 7479]]
7 (10061, 24) (10061, 24, 12)
     10061 [[0, 533], [534, 907], [908, 1592], [1593, 2541], [2542, 3435], [3436, 3625], [3626, 4137], [4138, 6058], [6059, 6765], [6766, 7287], [7288, 8390], [8391, 10060]]
8 (9674, 24) (9674, 24, 12)
     9674 [[0, 15], [16, 689], [690, 2664], [2665, 2781], [2782, 2945], [2946, 3907], [3908, 5848], [5849, 6489], [6490, 7417], [7418, 8903], [8904, 9673]]
9 (3346, 24) (3346, 24, 12)
     3346 [[0, 534], [535, 814], [815, 901], [902, 1071], [1072, 1928], [1929, 2220], [2221, 2913], [2914, 3345]]
10 (6529, 24) (6529, 24, 12)
     6529 [[0, 137], [138, 271], [272, 322], [323, 426], [427, 927], [928, 1406], [1407, 1887], [1888, 2100], [2101, 2382], [2383, 2621], [2622, 3702], [3703, 3811], [3812, 4028], [4029, 4079], [4080, 4216], [4217, 4334], [4335, 4418], [4419, 4524], [4525, 4677], [4678, 4814], [4815, 5053], [5054, 5273], [5274, 5332], [5333, 5401], [5402, 5623], [5624, 5719], [5720, 5903], [5904, 6327], [6328, 6528]]
11 (10422, 24) (10422, 24, 12)
     10422 [[0, 457], [458, 2411], [2412, 4126], [4127, 5880], [5881, 5947], [5948, 7243], [7244, 8639], [8640, 8845], [8846, 9022], [9023, 9343], [9344, 9880], [9881, 10421]]
12 (2531, 24) (2531, 24, 12)
     2531 [[0, 693], [694, 1416], [1417, 2197], [2198, 2530]]
13 (8229, 24) (8229, 24, 12)
     8229 [[0, 1352], [1353, 2560], [2561, 3227], [3228, 3867], [3868, 4171], [4172, 4331], [4332, 4449], [4450, 6125], [6126, 6741], [6742, 7294], [7295, 7328], [7331, 8037], [8038, 8228]]
14 (9281, 24) (9281, 24, 12)
     9281 [[0, 988], [989, 2928], [2929, 4058], [4059, 5142], [5143, 6002], [6003, 6890], [6891, 7191], [7192, 8590], [8591, 8638], [8639, 8983], [8984, 9280]]
15 (10226, 24) (10226, 24, 12)
     10226 [[0, 148], [149, 2116], [2117, 2267], [2268, 4246], [4247, 6200], [6201, 8169], [8170, 10112], [10113, 10172], [10173, 10225]]
16 (2713, 24) (2713, 24, 12)
     2713 [[0, 47], [48, 1130], [1131, 2094], [2095, 2712]]
17 (9147, 24) (9147, 24, 12)
     9147 [[0, 165], [166, 2105], [2106, 3800], [3801, 3994], [3995, 5954], [5955, 6875], [6876, 7384], [7385, 9146]]
18 (2731, 24) (2731, 24, 12)
     2731 [[0, 1221], [1222, 2730]]
19 (2534, 24) (2534, 24, 12)
     2534 [[0, 61], [62, 108], [109, 264], [265, 796], [797, 848], [849, 1558], [1559, 1803], [1804, 1809], [1810, 2533]]
20 (10262, 24) (10262, 24, 12)
     10262 [[0, 563], [564, 2019], [2020, 2507], [2508, 2850], [2851, 4806], [4807, 5675], [5676, 6350], [6351, 6951], [6952, 7363], [7364, 9306], [9307, 10261]]
21 (2298, 24) (2298, 24, 12)
     2298 [[0, 309], [310, 936], [937, 1577], [1578, 1592], [1593, 1602], [1603, 2186], [2187, 2297]]
22 (2768, 24) (2768, 24, 12)
     2768 [[0, 571], [572, 2026], [2027, 2509], [2510, 2767]]
23 (2644, 24) (2644, 24, 12)
     2644 [[0, 471], [472, 846], [847, 2643]]
24 (2690, 24) (2690, 24, 12)
     2690 [[0, 769], [770, 2253], [2254, 2689]]
25 (2335, 24) (2335, 24, 12)
     2335 [[0, 721], [722, 2334]]
26 (2719, 24) (2719, 24, 12)
     2719 [[0, 1257], [1258, 1481], [1482, 2718]]
27 (2892, 24) (2892, 24, 12)
     2892 [[0, 1164], [1165, 1624], [1625, 2144], [2145, 2891]]
28 (3211, 24) (3211, 24, 12)
     3211 [[0, 1091], [1092, 1405], [1406, 3210]]
29 (3021, 24) (3021, 24, 12)
     3021 [[0, 1482], [1483, 3020]]
30 (2540, 24) (2540, 24, 12)
     2540 [[0, 1257], [1258, 2539]]

In [29]:
gen_final(pid2valid_norm, attri2idx,  n_prev=24, pred_window=12, name='valid_pid2data_npy', valid_points = 12)

1 (2402, 24) (2402, 24, 12)
     2402 [[0, 1706], [1707, 2401]]
2 (11616, 24) (11616, 24, 12)
     11616 [[0, 350], [351, 2263], [2264, 4209], [4210, 6156], [6157, 6349], [6350, 7813], [7814, 8510], [8511, 10185], [10186, 10189], [10190, 11615]]
3 (9876, 24) (9876, 24, 12)
     9876 [[0, 165], [166, 663], [664, 1188], [1189, 1410], [1411, 1908], [1909, 3236], [3237, 5157], [5158, 5635], [5636, 7271], [7272, 9216], [9217, 9875]]
4 (11968, 24) (11968, 24, 12)
     11968 [[0, 836], [837, 2781], [2782, 2817], [2818, 4742], [4743, 6642], [6643, 8445], [8446, 8512], [8513, 10481], [10482, 11039], [11040, 11967]]
5 (11341, 24) (11341, 24, 12)
     11341 [[0, 847], [848, 1142], [1143, 2690], [2691, 4644], [4645, 6617], [6618, 8574], [8575, 10519], [10520, 11340]]
6 (7443, 24) (7443, 24, 12)
     7443 [[0, 482], [483, 1308], [1309, 3229], [3230, 3232], [3233, 3927], [3928, 5112], [5113, 7072], [7073, 7442]]
7 (9997, 24) (9997, 24, 12)
     9997 [[0, 528], [529, 896], [897, 1575], [1576, 2518], [2519, 3412], [3413, 3596], [3597, 4102], [4103, 6017], [6018, 6718], [6719, 7235], [7236, 8332], [8333, 9996]]
8 (9608, 24) (9608, 24, 12)
     9608 [[0, 9], [10, 677], [678, 2646], [2647, 2757], [2758, 2915], [2916, 3871], [3872, 5806], [5807, 6441], [6442, 7363], [7364, 8843], [8844, 9607]]
9 (3300, 24) (3300, 24, 12)
     3300 [[0, 528], [529, 804], [805, 885], [886, 1049], [1050, 1900], [1901, 2186], [2187, 2873], [2874, 3299]]
10 (6378, 24) (6378, 24, 12)
     6378 [[0, 131], [132, 259], [260, 304], [305, 402], [403, 897], [898, 1376], [1377, 1851], [1852, 2064], [2065, 2340], [2341, 2573], [2574, 3652], [3653, 3755], [3756, 3966], [3967, 4011], [4012, 4142], [4143, 4254], [4255, 4332], [4333, 4432], [4433, 4579], [4580, 4716], [4717, 4949], [4950, 5163], [5164, 5216], [5217, 5280], [5281, 5496], [5497, 5586], [5587, 5764], [5765, 6182], [6183, 6377]]
11 (10355, 24) (10355, 24, 12)
     10355 [[0, 451], [452, 2399], [2400, 4108], [4109, 5856], [5857, 5917], [5918, 7207], [7208, 8597], [8598, 8797], [8798, 8968], [8969, 9288], [9289, 9819], [9820, 10354]]
12 (2508, 24) (2508, 24, 12)
     2508 [[0, 687], [688, 1404], [1405, 2179], [2180, 2507]]
13 (8152, 24) (8152, 24, 12)
     8152 [[0, 1348], [1349, 2550], [2551, 3211], [3212, 3845], [3846, 4143], [4144, 4297], [4298, 4409], [4410, 6079], [6080, 6689], [6690, 7236], [7237, 7265], [7266, 7966], [7967, 8151]]
14 (9228, 24) (9228, 24, 12)
     9228 [[0, 982], [983, 2916], [2917, 4040], [4041, 5124], [5125, 5978], [5979, 6860], [6861, 7155], [7156, 8554], [8555, 8596], [8597, 8936], [8937, 9227]]
15 (10172, 24) (10172, 24, 12)
     10172 [[0, 142], [143, 2104], [2105, 2249], [2250, 4222], [4223, 6170], [6171, 8133], [8134, 10070], [10071, 10124], [10125, 10171]]
16 (2692, 24) (2692, 24, 12)
     2692 [[0, 41], [42, 1118], [1119, 2078], [2080, 2691]]
17 (9099, 24) (9099, 24, 12)
     9099 [[0, 159], [160, 2093], [2094, 3782], [3783, 3970], [3971, 5924], [5925, 6839], [6840, 7342], [7343, 9098]]
18 (2719, 24) (2719, 24, 12)
     2719 [[0, 1215], [1216, 2718]]
19 (2500, 24) (2500, 24, 12)
     2500 [[0, 55], [56, 96], [97, 252], [253, 778], [779, 830], [831, 1536], [1537, 1781], [1782, 2499]]
20 (10210, 24) (10210, 24, 12)
     10210 [[0, 557], [558, 2008], [2009, 2490], [2491, 2828], [2829, 4778], [4779, 5641], [5642, 6316], [6317, 6917], [6918, 7323], [7324, 9260], [9261, 10209]]
21 (2267, 24) (2267, 24, 12)
     2267 [[0, 303], [304, 924], [925, 1559], [1560, 1570], [1571, 1581], [1582, 2159], [2160, 2266]]
22 (2750, 24) (2750, 24, 12)
     2750 [[0, 565], [566, 2020], [2021, 2497], [2498, 2749]]
23 (2632, 24) (2632, 24, 12)
     2632 [[0, 471], [472, 840], [841, 2631]]
24 (2673, 24) (2673, 24, 12)
     2673 [[0, 763], [764, 2241], [2242, 2672]]
25 (2324, 24) (2324, 24, 12)
     2324 [[0, 716], [717, 2323]]
26 (2701, 24) (2701, 24, 12)
     2701 [[0, 1251], [1252, 1469], [1470, 2700]]
27 (2871, 24) (2871, 24, 12)
     2871 [[0, 1158], [1159, 1615], [1616, 2129], [2130, 2870]]
28 (3199, 24) (3199, 24, 12)
     3199 [[0, 1091], [1092, 1399], [1400, 3198]]
29 (3009, 24) (3009, 24, 12)
     3009 [[0, 1476], [1477, 3008]]
30 (2528, 24) (2528, 24, 12)
     2528 [[0, 1251], [1252, 2527]]

In [30]:
gen_final(pid2test_norm, attri2idx,  n_prev=24, pred_window=6, name='test_pid2data_npy', valid_points = 12)

1 (2406, 24) (2406, 24, 12)
     2406 [[0, 333], [334, 1439], [1440, 2405]]
2 (11680, 24) (11680, 24, 12)
     11680 [[0, 56], [57, 1967], [1968, 3875], [3876, 5833], [5834, 7776], [7777, 9719], [9720, 11679]]
3 (9917, 24) (9917, 24, 12)
     9917 [[0, 231], [232, 883], [884, 989], [990, 2451], [2452, 2893], [2894, 4856], [4857, 6827], [6828, 8207], [8208, 9097], [9098, 9916]]
4 (12020, 24) (12020, 24, 12)
     12020 [[0, 944], [945, 2871], [2872, 4777], [4778, 6738], [6739, 8663], [8664, 9029], [9030, 10287], [10288, 12019]]
5 (11376, 24) (11376, 24, 12)
     11376 [[0, 662], [663, 1744], [1745, 3714], [3715, 5667], [5668, 5718], [5719, 5944], [5945, 7683], [7684, 9636], [9637, 11375]]
6 (7456, 24) (7456, 24, 12)
     7456 [[0, 1477], [1478, 1873], [1874, 2153], [2154, 3635], [3636, 4048], [4049, 4528], [4529, 6454], [6455, 7455]]
7 (10018, 24) (10018, 24, 12)
     10018 [[0, 114], [115, 643], [644, 652], [653, 693], [694, 1403], [1404, 1496], [1497, 1682], [1683, 3588], [3589, 4008], [4009, 4313], [4314, 6153], [6154, 6714], [6715, 6844], [6845, 6858], [6859, 6913], [6914, 6916], [6917, 7460], [7461, 8214], [8215, 9816], [9817, 10017]]
8 (9785, 24) (9785, 24, 12)
     9785 [[0, 64], [65, 2008], [2009, 3969], [3970, 5934], [5935, 7242], [7243, 7311], [7312, 7742], [7743, 9702], [9703, 9784]]
9 (3270, 24) (3270, 24, 12)
     3270 [[0, 393], [394, 397], [398, 519], [520, 633], [636, 677], [678, 683], [684, 779], [780, 1032], [1033, 1334], [1335, 1827], [1828, 1836], [1837, 2477], [2478, 3269]]
10 (6573, 24) (6573, 24, 12)
     6573 [[0, 372], [373, 626], [627, 867], [868, 964], [965, 1165], [1166, 1397], [1398, 1607], [1608, 1848], [1849, 2085], [2086, 2310], [2311, 2482], [2483, 2714], [2715, 2925], [2926, 3035], [3036, 3245], [3246, 3377], [3378, 3687], [3688, 3914], [3915, 4126], [4127, 4388], [4389, 4628], [4629, 4640], [4641, 4863], [4864, 4981], [4982, 5232], [5233, 5761], [5762, 5994], [5995, 6233], [6234, 6319], [6320, 6409], [6410, 6572]]
11 (10452, 24) (10452, 24, 12)
     10452 [[0, 1203], [1204, 3180], [3181, 3457], [3458, 4870], [4871, 5093], [5094, 7068], [7069, 8689], [8690, 10451]]
12 (2538, 24) (2538, 24, 12)
     2538 [[0, 782], [783, 1501], [1502, 2537]]
13 (8413, 24) (8413, 24, 12)
     8413 [[0, 1716], [1717, 3679], [3680, 3806], [3807, 3965], [3966, 5359], [5360, 5840], [5841, 7023], [7024, 7704], [7705, 8412]]
14 (9324, 24) (9324, 24, 12)
     9324 [[0, 1017], [1018, 1065], [1066, 2165], [2166, 3470], [3471, 4048], [4049, 4496], [4497, 4791], [4792, 6613], [6614, 6876], [6877, 8239], [8240, 9323]]
15 (10262, 24) (10262, 24, 12)
     10262 [[0, 1699], [1700, 1792], [1793, 2198], [2199, 4134], [4135, 4718], [4719, 6385], [6386, 8369], [8370, 10261]]
16 (2759, 24) (2759, 24, 12)
     2759 [[0, 1069], [1070, 2758]]
17 (9148, 24) (9148, 24, 12)
     9148 [[0, 168], [169, 2111], [2112, 4065], [4066, 6015], [6016, 6381], [6382, 7266], [7267, 7843], [7844, 8875], [8876, 9147]]
18 (2724, 24) (2724, 24, 12)
     2724 [[0, 438], [439, 2422], [2423, 2723]]
19 (2565, 24) (2565, 24, 12)
     2565 [[0, 1227], [1228, 1569], [1570, 1609], [1610, 1752], [1753, 1768], [1769, 1799], [1800, 2564]]
20 (10116, 24) (10116, 24, 12)
     10116 [[0, 984], [985, 2904], [2905, 4870], [4871, 5452], [5453, 5532], [5533, 6328], [6329, 6727], [6728, 6849], [6850, 7781], [7782, 8369], [8370, 10115]]
21 (2325, 24) (2325, 24, 12)
     2325 [[0, 252], [253, 952], [953, 2324]]
22 (2744, 24) (2744, 24, 12)
     2744 [[0, 774], [775, 1169], [1170, 2381], [2382, 2743]]
23 (2642, 24) (2642, 24, 12)
     2642 [[0, 113], [114, 1995], [1996, 2641]]
24 (2696, 24) (2696, 24, 12)
     2696 [[0, 936], [937, 2695]]
25 (2328, 24) (2328, 24, 12)
     2328 [[0, 26], [27, 1956], [1957, 2327]]
26 (2709, 24) (2709, 24, 12)
     2709 [[0, 665], [666, 1101], [1102, 2106], [2107, 2356], [2357, 2708]]
27 (2912, 24) (2912, 24, 12)
     2912 [[0, 183], [184, 765], [766, 1462], [1463, 1963], [1964, 2911]]
28 (3180, 24) (3180, 24, 12)
     3180 [[0, 96], [97, 1547], [1548, 1724], [1725, 1729], [1730, 1932], [1933, 3179]]
29 (3009, 24) (3009, 24, 12)
     3009 [[0, 406], [407, 475], [476, 2346], [2347, 3008]]
30 (2540, 24) (2540, 24, 12)
     2540 [[0, 641], [642, 2539]]

In [31]:
gen_final(pid2test_norm, attri2idx,  n_prev=24, pred_window=12, name='test_pid2data_npy', valid_points = 12)

1 (2388, 24) (2388, 24, 12)
     2388 [[0, 327], [328, 1427], [1428, 2387]]
2 (11638, 24) (11638, 24, 12)
     11638 [[0, 50], [51, 1955], [1956, 3857], [3858, 5809], [5810, 7746], [7747, 9683], [9684, 11637]]
3 (9857, 24) (9857, 24, 12)
     9857 [[0, 225], [226, 871], [872, 971], [972, 2427], [2428, 2863], [2864, 4820], [4821, 6785], [6786, 8159], [8160, 9043], [9044, 9856]]
4 (11973, 24) (11973, 24, 12)
     11973 [[0, 938], [939, 2859], [2860, 4759], [4760, 6714], [6715, 8633], [8634, 8993], [8994, 10246], [10247, 11972]]
5 (11322, 24) (11322, 24, 12)
     11322 [[0, 656], [657, 1732], [1733, 3696], [3697, 5643], [5644, 5688], [5689, 5908], [5909, 7641], [7642, 9588], [9589, 11321]]
6 (7408, 24) (7408, 24, 12)
     7408 [[0, 1471], [1472, 1861], [1862, 2135], [2136, 3611], [3612, 4018], [4019, 4492], [4493, 6412], [6413, 7407]]
7 (9920, 24) (9920, 24, 12)
     9920 [[0, 108], [109, 635], [636, 642], [643, 681], [682, 1385], [1386, 1472], [1473, 1652], [1653, 3552], [3553, 3966], [3967, 4265], [4266, 6099], [6100, 6654], [6655, 6778], [6779, 6786], [6787, 6835], [6836, 7373], [7374, 8121], [8122, 9724], [9725, 9919]]
8 (9732, 24) (9732, 24, 12)
     9732 [[0, 58], [59, 1996], [1997, 3951], [3952, 5910], [5911, 7212], [7213, 7275], [7276, 7701], [7702, 9655], [9656, 9731]]
9 (3214, 24) (3214, 24, 12)
     3214 [[0, 387], [388, 503], [504, 611], [612, 619], [620, 656], [657, 746], [748, 1000], [1001, 1296], [1297, 1789], [1790, 1792], [1793, 2427], [2428, 3213]]
10 (6400, 24) (6400, 24, 12)
     6400 [[0, 368], [369, 616], [617, 851], [852, 942], [943, 1137], [1138, 1363], [1364, 1567], [1568, 1808], [1809, 2039], [2040, 2258], [2259, 2424], [2425, 2650], [2651, 2855], [2856, 2959], [2960, 3163], [3164, 3289], [3290, 3593], [3594, 3814], [3815, 4020], [4021, 4277], [4278, 4511], [4512, 4517], [4518, 4736], [4737, 4848], [4849, 5094], [5095, 5617], [5618, 5844], [5845, 6077], [6078, 6157], [6158, 6242], [6243, 6399]]
11 (10407, 24) (10407, 24, 12)
     10407 [[0, 1197], [1198, 3168], [3169, 3442], [3443, 4849], [4850, 5066], [5067, 7035], [7036, 8650], [8651, 10406]]
12 (2526, 24) (2526, 24, 12)
     2526 [[0, 782], [783, 1495], [1496, 2525]]
13 (8366, 24) (8366, 24, 12)
     8366 [[0, 1710], [1711, 3669], [3670, 3795], [3796, 3948], [3949, 5336], [5337, 5811], [5812, 6988], [6989, 7663], [7664, 8365]]
14 (9268, 24) (9268, 24, 12)
     9268 [[0, 1015], [1016, 1057], [1058, 2151], [2152, 3450], [3451, 4022], [4023, 4470], [4471, 4759], [4760, 6575], [6576, 6832], [6833, 8189], [8190, 9267]]
15 (10215, 24) (10215, 24, 12)
     10215 [[0, 1693], [1694, 1780], [1781, 2180], [2181, 4110], [4111, 4689], [4690, 6350], [6351, 8328], [8329, 10214]]
16 (2747, 24) (2747, 24, 12)
     2747 [[0, 1063], [1064, 2746]]
17 (9095, 24) (9095, 24, 12)
     9095 [[0, 162], [163, 2099], [2100, 4047], [4048, 5991], [5992, 6351], [6352, 7231], [7232, 7802], [7803, 8828], [8829, 9094]]
18 (2706, 24) (2706, 24, 12)
     2706 [[0, 432], [433, 2410], [2411, 2705]]
19 (2546, 24) (2546, 24, 12)
     2546 [[0, 1221], [1222, 1563], [1564, 1603], [1604, 1745], [1746, 1755], [1756, 1786], [1787, 2545]]
20 (10052, 24) (10052, 24, 12)
     10052 [[0, 978], [979, 2892], [2893, 4852], [4853, 5428], [5429, 5504], [5505, 6294], [6295, 6687], [6688, 6803], [6804, 7729], [7730, 8311], [8312, 10051]]
21 (2313, 24) (2313, 24, 12)
     2313 [[0, 252], [253, 946], [947, 2312]]
22 (2720, 24) (2720, 24, 12)
     2720 [[0, 768], [769, 1157], [1158, 2363], [2364, 2719]]
23 (2624, 24) (2624, 24, 12)
     2624 [[0, 107], [108, 1983], [1984, 2623]]
24 (2684, 24) (2684, 24, 12)
     2684 [[0, 930], [931, 2683]]
25 (2310, 24) (2310, 24, 12)
     2310 [[0, 20], [21, 1944], [1945, 2309]]
26 (2685, 24) (2685, 24, 12)
     2685 [[0, 659], [660, 1089], [1090, 2088], [2089, 2338], [2339, 2684]]
27 (2888, 24) (2888, 24, 12)
     2888 [[0, 177], [178, 753], [754, 1450], [1451, 1945], [1946, 2887]]
28 (3161, 24) (3161, 24, 12)
     3161 [[0, 90], [91, 1541], [1542, 1712], [1713, 1722], [1723, 1919], [1920, 3160]]
29 (2995, 24) (2995, 24, 12)
     2995 [[0, 400], [401, 468], [469, 2338], [2339, 2994]]
30 (2528, 24) (2528, 24, 12)
     2528 [[0, 635], [636, 2527]]